//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 xy2simulator.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_XY2SIMULATOR_DIALOG         102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDC_LIST1                       1000
#define IDC_BT_W_JIAWU                  1001
#define IDC_BT_W_BANDU                  1002
#define IDC_BT_W_HUOGONG                1003
#define IDC_BT_W_SHUISHOU               1004
#define IDC_BT_W_SHOUYIN                1005
#define IDC_EDIT_QIZHI                  1006
#define IDC_EDIT_NEILI                  1007
#define IDC_EDIT_ZHILI                  1008
#define IDC_EDIT_NAILI                  1009
#define IDC_EDIT_MINGQI                 1010
#define IDC_EDIT_DAODE                  1011
#define IDC_EDIT_PANNI                  1012
#define IDC_EDIT_PILAO                  1013
#define IDC_EDIT_WANXING                1014
#define IDC_EDIT_JINQIAN                1015
#define IDC_BT_W_JIANYAO                1015
#define IDC_BT_W_YINLU                  1016
#define IDC_EDIT_QIZHI2                 1017
#define IDC_EDIT_NEILI2                 1018
#define IDC_EDIT_ZHILI2                 1019
#define IDC_EDIT_NAILI2                 1020
#define IDC_EDIT_MINGQI2                1021
#define IDC_EDIT_DAODE2                 1022
#define IDC_EDIT_PANNI2                 1023
#define IDC_BT_W_XIAOFAN                1024
#define IDC_BT_W_DASOU                  1025
#define IDC_BT_W_DASHOU                 1025
#define IDC_EDIT_QIZHI3                 1026
#define IDC_EDIT_NEILI3                 1027
#define IDC_EDIT_ZHILI3                 1028
#define IDC_EDIT_NAILI3                 1029
#define IDC_EDIT_MINGQI3                1030
#define IDC_EDIT_DAODE3                 1031
#define IDC_EDIT_PANNI3                 1032
#define IDC_EDIT_PILAO3                 1033
#define IDC_EDIT_PILAO2                 1034
#define IDC_BT_W_PAOTANG                1034
#define IDC_EDIT_WANXING2               1035
#define IDC_BT_L_ZAIJIA                 1035
#define IDC_EDIT_JINQIAN2               1036
#define IDC_BT_L_GUOZIJIAN              1036
#define IDC_EDIT_WANXING3               1037
#define IDC_EDIT_JINQIAN3               1038
#define IDC_EDIT_SUI                    1039
#define IDC_EDIT_YUE                    1040
#define IDC_EDIT_YUE2                   1041
#define IDC_EDIT_CI                     1041
#define IDC_BT_PINGJIA                  1042
#define IDC_BT_CHUSHIHUA                1043
#define IDC_EDIT_PINGJIA                1044
#define IDC_BT_L_HUANGGONG              1045
#define IDC_BT_L_HAIBIAN                1046
#define IDC_BT_L_YEWAI                  1047
#define IDC_BT_L_TAIYIYUAN              1048
#define IDC_BT_L_DIFU                   1049
#define IDC_BT_L_HEISHI                 1050
#define IDC_BT_L_DUCHANG                1051
#define IDC_BT_L_LVYOU                  1052
#define IDC_BT_L_QINGLOU                1053
#define IDC_BT_W_MAIMENG                1054
#define IDC_BT_S_MEISHU                 1055
#define IDC_BT_S_YINLV                  1056
#define IDC_BT_S_SHIWEN                 1057
#define IDC_BT_S_WUSHU                  1058
#define IDC_BT_S_WUDAO                  1059
#define IDC_BT_S_JIANZHU                1060
#define IDC_BT_S_ZONGJIAO               1061
#define IDC_BT_S_QISHU                  1062
#define IDC_EDIT_XIAOHAOJINQIAN         1063
#define IDC_EDIT_XIAOHAOSHIMEN          1064
#define IDC_EDIT_QIZHI4                 1065
#define IDC_EDIT_BANDU                  1066
#define IDC_EDIT_SHOUYIN                1067
#define IDC_EDIT_DASHOU                 1068
#define IDC_EDIT_ZUOJIAWU               1069
#define IDC_EDIT_JIANYAO                1070
#define IDC_EDIT_MAIMENG                1071
#define IDC_EDIT_HUOGONG                1072
#define IDC_EDIT_SHUISHOU               1073
#define IDC_EDIT_YINLU                  1074
#define IDC_EDIT_PAOTANG                1075
#define IDC_EDIT_XIAOFAN                1076
#define IDC_EDIT_GUOZIJIAN              1077
#define IDC_EDIT_YEWAI                  1078
#define IDC_EDIT_DUCHANG                1079
#define IDC_EDIT_XIUXI                  1080
#define IDC_EDIT_TAIYIYUAN              1081
#define IDC_EDIT_LVYOU                  1082
#define IDC_EDIT_HUANGGONG              1083
#define IDC_EDIT_DIFU                   1084
#define IDC_EDIT_QINGLOU                1085
#define IDC_EDIT_HAIBIAN                1086
#define IDC_EDIT_HEISHI                 1087
#define IDC_EDIT_YINLV                  1088
#define IDC_EDIT_WUDAO                  1089
#define IDC_EDIT_MEISHU                 1090
#define IDC_EDIT_JIANZHU                1091
#define IDC_EDIT_SHIWEN                 1092
#define IDC_EDIT_ZONGJIAO               1093
#define IDC_EDIT_WUSHU                  1094
#define IDC_EDIT_QISHU                  1095
#define IDC_EDIT_NEILI4                 1096
#define IDC_EDIT_ZHILI4                 1097
#define IDC_EDIT_NAILI4                 1098
#define IDC_EDIT_MINGQI4                1099
#define IDC_EDIT_DAODE4                 1100
#define IDC_EDIT_PANNI4                 1101
#define IDC_EDIT_PILAO4                 1102
#define IDC_EDIT_WANXING4               1103
#define IDC_EDIT_JINQIAN4               1104
#define IDC_EDIT_SUI2                   1105
#define IDC_EDIT_YUE3                   1106
#define IDC_EDIT_CI2                    1107
#define IDC_BT_QINGLING                 1108

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
